export enum UserRegistrationStep {
  PERSONAL_DATA = 0,
  INFORM_WANTS_PERSONALIZATION = 1,
  GENDER = 2,
  MAIN_GOAL = 3,
  MAIN_GOAL_CURRENT_LEVEL = 4,
  INTEREST_ACTIVITIES = 5,
  FINGERPRINT_ACCESS = 6,
  NONE = 7,
}
